cars_auto = subset(mtcars, am == 0)
cars_gear = subset(mtcars, am == 1)
dim(mtcars)
dim(cars_auto) ; dim(cars_gear)
mean(cars_auto$mpg); mean(cars_gear$mpg)
sd(cars_auto$mpg) ; sd(cars_gear$mpg)
t.test(cars_gear$mpg, cars_auto$mpg, paired = F, var.equal = F)
hist(mtcars$mpg, col = "red")
hist(mtcars$cyl, col = "red")
hist(mtcars$disp, col = "blue")
hist(mtcars$hp, col = "blue")
hist(mtcars$drat, col = "green")
hist(mtcars$wt, col = "green")
hist(mtcars$qsec, col = "brown")
hist(mtcars$vs, col = "brown")
hist(mtcars$am, col = "black")
hist(mtcars$gear, col = "red")
hist(mtcars$carb, col = "red")
boxplot(mtcars, main = "value of all variables", xlab = "mtcars", col = "red")
